// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD84shd1Kf02ZOgdVWlAiw9Wk-WXZdQOQU',
    appId: '1:213981535486:web:f59ed8fab5f2d89dc119af',
    messagingSenderId: '213981535486',
    projectId: 'fluttercrud-89810',
    authDomain: 'fluttercrud-89810.firebaseapp.com',
    storageBucket: 'fluttercrud-89810.appspot.com',
    measurementId: 'G-E3N9GX6WVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_ORxZx0a_g2OCMY4SxK1I--2fWqOx8AA',
    appId: '1:213981535486:android:3c6c620fe43160a5c119af',
    messagingSenderId: '213981535486',
    projectId: 'fluttercrud-89810',
    storageBucket: 'fluttercrud-89810.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjENQFrU0f6xggMUxVp4nZIgStqaTBoT8',
    appId: '1:213981535486:ios:d5408badd6774c78c119af',
    messagingSenderId: '213981535486',
    projectId: 'fluttercrud-89810',
    storageBucket: 'fluttercrud-89810.appspot.com',
    androidClientId: '213981535486-0jn1nk8bovv8nqms614k6smd6q6q3eao.apps.googleusercontent.com',
    iosClientId: '213981535486-mp17badahb2ejqa8gk79e0hkqlu1i8ks.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreCrud',
  );
}
